#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RESOURCES_DIR="$SCRIPT_DIR/../Resources"

# 必要なPythonパッケージをインストール
cd "$RESOURCES_DIR"
python3 -m pip install -q python-dotenv flask requests selenium webdriver_manager supabase

# アプリケーションを起動
python3 "$RESOURCES_DIR/app_launcher.py"
